version: '3'

services:
  projetomod4:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'projetomod4'
    restart: always
    volumes:
      - projetomod4-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: userprojmod
      POSTGRES_PASSWORD: projmod4

volumes:
  projetomod4-data:
